FROM node:13-alpine as node

RUN mkdir /app
WORKDIR /app
COPY ./frontend/package.json /app
COPY ./frontend/package-lock.json /app
RUN npm i
COPY ./frontend /app
RUN npm run build

FROM nginx:1.17.5
COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=node /app/dist /app/public
